server: 
  port: 8080 

spring: 
  thymeleaf: 
    prefix: classpath:/templates/
          
  mvc:
    static-path-pattern: /**

  servlet:
    multipart: 
      max-file-size: 30MB
      max-request-size: 30MB
      location: /tmp
          
        